#! /bin/bash

set -eo pipefail

echo '[pre-commit] Generating Helm docs...'

helm-docs 2> /dev/null

[[ $(git diff charts/*/README.md) ]] && (echo 'ERROR: Helm documentation updated!' && exit 1)

echo '[pre-commit] Running chart testing...'

ct lint --config ./.ct.yml > /dev/null

echo '[pre-commit] Running Helm template...'

for chart in ./charts/*; do
  helm template "$chart" > /dev/null
done

exit 0
